<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32704" started-at="2019-11-04T16:26:32Z" finished-at="2019-11-04T16:27:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32704" started-at="2019-11-04T16:26:32Z" finished-at="2019-11-04T16:27:05Z">
      <class name="test.LoginTest">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:test.LoginTest@26653222]" name="startBrowser" is-config="true" duration-ms="7083" started-at="2019-11-04T16:26:32Z" finished-at="2019-11-04T16:26:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="validUserShouldBeAbleToLogin()[pri:1, instance:test.LoginTest@26653222]" name="validUserShouldBeAbleToLogin" duration-ms="2869" started-at="2019-11-04T16:26:39Z" finished-at="2019-11-04T16:26:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong page! expected [Dashboard ‹ opensourcecms — Wordpress] but found [Dashboard ‹ opensourcecms — WordPress]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong page! expected [Dashboard ‹ opensourcecms — Wordpress] but found [Dashboard ‹ opensourcecms — WordPress]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at test.LoginTest.validUserShouldBeAbleToLogin(LoginTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserShouldBeAbleToLogin -->
        <test-method status="PASS" signature="close()[pri:0, instance:test.LoginTest@26653222]" name="close" is-config="true" duration-ms="4883" started-at="2019-11-04T16:26:42Z" finished-at="2019-11-04T16:26:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:test.LoginTest@26653222]" name="startBrowser" is-config="true" duration-ms="6096" started-at="2019-11-04T16:26:47Z" finished-at="2019-11-04T16:26:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="PASS" signature="invalidUserShouldNotBeAbleToLogin()[pri:2, instance:test.LoginTest@26653222]" name="invalidUserShouldNotBeAbleToLogin" duration-ms="11017" started-at="2019-11-04T16:26:53Z" finished-at="2019-11-04T16:27:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserShouldNotBeAbleToLogin -->
        <test-method status="PASS" signature="close()[pri:0, instance:test.LoginTest@26653222]" name="close" is-config="true" duration-ms="726" started-at="2019-11-04T16:27:04Z" finished-at="2019-11-04T16:27:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
